<?php
/**
 * Created by PhpStorm.
 * User: hp
 * Date: 2019/10/14
 * Time: 18:16
 */

namespace app\index\controller;


use think\Db;

class Category extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {

        $cid = $this->request->get('cid');
        $currnav = Db::table('navlnsert')->where('id', $cid)->find();
        $tpl = $currnav['ntpl'];
        $this->assign('name', $currnav['name']);
        $this->assign('cid', $cid);
        $this->assign('currnav', $currnav);
//        产品中心代码
        $navdata2 = Db::table('cateselect')->select();
        $navdata1 = [["id" => '0', "cname" => "全部", 'cid' => '-1']];
        $navdata = array_merge($navdata1, $navdata2);
        $this->assign('navdata',$navdata);
        $data = Db::table('goods')->select();
        $this->assign('data',$data);
        $count = count($navdata);
        for ($i = 0; $i < $count; $i++) {
            if ($i == 0) {
                $datas[$i] = $data;
                continue;
            }
            $key0 = $navdata[$i];
            $id = $key0['id'];
            $va = array_filter($data, function ($v) use ($id) {
                return $v['cid'] == $id;
            });
            $datas[$i] = $va;
        }
        $this->assign('datas',$datas);
//      新闻资讯
        $id = $this->request->get('cid');
        $news=Db::table('news')->select();
        $this->assign('news',$news);
        //       服务项目
        $id = $this->request->get('cid');
        $service=Db::table('service')->select();
        $this->assign('service',$service);
//        关于我们
        $id = $this->request->get('id');
        $about=Db::table('about')->find();
        $this->assign('about',$about);
//        人员介绍
        $personnel=Db::table('personnel')->select();
        $this->assign('personnel',$personnel);
        return $this->fetch($tpl);
    }

    public function insert()
    {
        //权限 请求方式 参数
        $data = input('post.');
        $result = Db::table('online')->insert($data);
        $method = $this->request->method();
        if ($method != 'POST') {
            return json(['code' => 404, 'msg' => '请求失败']);
        }
        if ($result > 0) {
            return json(['code' => 200, 'msg' => '插入成功']);
        } else {
            return json(['code' => 404, 'msg' => '插入失败']);
        }
    }

    public function goods()
    {
        $this->assign('cid', 8);
        $this->assign('title',  '产品');
        $id = $this->request->get('id');
        $goods=Db::table('goods')->where('id',$id)->find();
        $gbanner=explode(',',$goods['gbanner']);
        $this->assign('gbanner',$gbanner);
        $this->assign('goods',$goods);
//        var_dump($gbanner);
        return $this->fetch();
    }
    public function page()
    {
        $this->assign('cid', 7);
        $this->assign('title',  '新闻资讯');
        $id = $this->request->get('id');
        $page=Db::table('news')->where('nid',$id)->find();
//        上一篇开始
//        $id=$_GET['id'];
        $next1=Db::table('news')->where('nid','<',$id)->order('nid','asc')
            ->limit('0','1')->find();
        $next2=Db::table('news')->where('nid','>',$id)->order('nid','desc')
            ->limit('0','1')->find();
        if (!$next1){
        $next1['nname']="没有了";
        $next1['nid']=106;
    }
        if (!$next2){
            $next1['nname']="没有了";
            $next1['nid']=110;
        }
        $this->assign('page',$page);
        $this->assign('next1',$next1);
        $this->assign('next2',$next2);
        return $this->fetch();
    }
}