<?php

namespace app\index\controller;


use think\Db;

class Index extends Base
{
    public function _initialize()
    {
        return parent::_initialize(); // TODO: Change the autogenerated stub

    }
    public  function  index(){

        $this->assign('cid',0);
        $service=Db::table('service')->select();
        $this->assign('service',$service);
        $about=Db::table('about')->find();
        $this->assign('about',$about);
        $news=Db::table('news')->select();
        $this->assign('news',$news);
        return $this->fetch();
    }
}
