<?php
/**
 * Created by PhpStorm.
 * User: hp
 * Date: 2019/10/21
 * Time: 23:00
 */

namespace app\admin\controller;


use think\Db;

class About extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function open()
    {
        $about = Db::table('about')->select();
        $this->assign('about', $about);
        return $this->fetch();
    }

    public function index()
    {
        $about = Db::table('about')->select();
        $this->assign('about', $about);
        return $this->fetch();
    }

    public function insert()
    {
        $fieldta = input('post.');
        $result = Db::table('about')->insert($fieldta);
        var_dump($result);
        if ($result > 0) {
            return json(['code' => 200, 'msg' => '插入成功']);
        } else {
            return json(['code' => 404, 'msg' => '插入失败']);
        }
    }

    public function query()
    {
        $result = Db::table('about')->select();
        $count = Db::table('about')->count();
        return json([
            'code' => 0,
            'msg' => 'success',
            'data' => $result,
            'count' => $count,
        ]);
    }

    //删除开始
    public function delete()
    {
//        $del=Db::table('navlnsert')->delete();
        if (!$this->request->isPost()) {
            return json(['code' => 404, 'msg' => '请求失败']);
        }
//        验证规则
        $fieldta = input('post.');
        $validate = validate('Nav');
        if (!$validate->scene('del')->check($fieldta)) {
            return json(['code' => 404, 'msg' => $validate->getError()]);
        }
        $result = Db::name('about')->where('sid', $fieldta['id'])->delete();
        if ($result > 0) {
            return json(['code' => 200, 'msg' => '删除成功']);
        } else {
            return json(['code' => 404, 'msg' => '删除失败']);
        }
    }

    //    修改开始
    public function add()
    {
        if (!$this->request->isPost()) {
            return json(['code' => 404, 'msg' => '请求失败']);
        }
//        验证规则
        $fieldta = input('post.');
        $validate = validate('Nav');
        if (!$validate->scene('update')->check($fieldta)) {
            return json(['code' => 404, 'msg' => $validate->getError()]);
        };
//        $del=Db::table('navlnsert')->delete();
        $id = input('post.id');
        $value = input('post.value');
        $field = input('post.field');
        $result = Db::name('about')->where('sid', $id)->update([$field => $value]);
        if ($result > 0) {
            return json(['code' => 200, 'msg' => '修改成功']);
        } else {
            return json(['code' => 404, 'msg' => '修改失败']);
        }
    }

}