<?php
/**
 * Created by PhpStorm.
 * User: hp
 * Date: 2019/10/14
 * Time: 11:18
 */

namespace app\admin\controller;


use think\Controller;
use think\Session;

class Base extends  Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!Session::has('username')){
            $this->error('请登录','home/public/index.php/admin/login/index');
            exit();
        }
    }

}