<?php
/**
 * Created by PhpStorm.
 * User: hp
 * Date: 2019/10/9
 * Time: 16:22
 */

namespace app\admin\controller;


use think\Session;

class Main extends Base
{
    public function  _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function index (){
        $username=Session::get('username');
//        var_dump($username);
        return view('index',['username'=>$username]);
    }
}