<?php
/**
 * Created by PhpStorm.
 * User: hp
 * Date: 2019/10/17
 * Time: 22:08
 */

namespace app\admin\controller;


use think\Db;

class Online extends Base
{
    public function  _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function index (){
        return $this->fetch();
    }
//    展示插入页面
//    展示插入页面
    public function open (){
        return view();
    }
    public function insert (){
        //权限 请求方式 参数
        $data=input('post.');
        $data['odate']=date('Y-m-d h:m:s');
        $result=Db::table('online')->insert($data);
        $method=$this->request->method();
        if ($method !='POST'){
            return json(['code'=>404,'msg'=>'请求失败']);
        }
//        验证规则
//        $validate = validate('Nav');
//        if (!$validate->scene('insert')->check($data))
//        {
//            return json(['code'=>404,'msg'=>$validate->getError()]);
//        };
        if ($result>0){
            return json(['code'=>200,'msg'=>'插入成功']);
        }
        else{
            return json(['code'=>404,'msg'=>'插入失败']);
        }
    }
    public function query(){
        $result=Db::table('online')->select();
        $count=Db::table('online')->count();
        return json([
            'code'=>0,
            'msg'=>'success',
            'data'=>$result,
            'count'=>$count,
        ]);
    }
    public function delete(){
//        $del=Db::table('navlnsert')->delete();
        if (!$this->request->isPost()){
            return json(['code'=>404,'msg'=>'请求失败']);
        }
//        验证规则
        $data=input('post.');
        $validate = validate('Nav');
        if (!$validate->scene('del')->check($data))
        {
            return json(['code'=>404,'msg'=>$validate->getError()]);
        };
        $result= Db::name('online')	->where('id',	$data['id'])->delete();
        if ($result>0){
            return json(['code'=>200,'msg'=>'删除成功']);
        }
        else{
            return json(['code'=>404,'msg'=>'删除失败']);
        }
    }
//    修改开始
    public function add(){
        if (!$this->request->isPost()){
            return json(['code'=>404,'msg'=>'请求失败']);
        }
//        验证规则
        $data=input('post.');
        $validate = validate('Nav');
        if (!$validate->scene('update')->check($data))
        {
            return json(['code'=>404,'msg'=>$validate->getError()]);
        };
//        $del=Db::table('navlnsert')->delete();
        $id=input('post.id');
        $value=input('post.value');
        $field=input('post.field');
        $result= Db::name('online')->where('id',$id)	->update([$field=>$value]);
        if ($result>0){
            return json(['code'=>200,'msg'=>'修改成功']);
        }
        else{
            return json(['code'=>404,'msg'=>'修改失败']);
        }
    }
}