<?php
/**
 * Created by PhpStorm.
 * User: hp
 * Date: 2019/10/11
 * Time: 15:46
 */

namespace app\admin\controller;


class Upload extends Base
{
    public function  _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function index(){
        // 获取表单上传文件 例如上传了001.jpg
        $file = request()->file('file');

        // 移动到框架应用根目录/public/uploads/ 目录下
        $info = $file->validate(['size'=>500*1024,'ext'=>'jpg,png,gif，webp，jpeg'])->move(ROOT_PATH . 'public' . DS . 'uploads');
        if($info){
            // 成功上传后 获取上传信息

                $src=UPLOAD_PATH.$info->getSaveName();
//                ;
            return json([
                'code'=> 0,
                'msg'=>'上传成功',
                 'data'=> ['src'=>$src
                 ],
            ]);
        }else{
            // 上传失败获取错误信息
            echo $file->getError();
        }
    }
}